name: Battle Box Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      env:
        MIX_ENV: test
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.0
        otp-version: 22.2
    - name: Install Dependencies
      run: MIX_ENV=test mix deps.get
    - name: Run Tests
      run: mix test
