name: Battle Box Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.6-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      env:
        MIX_ENV: test
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.0
        otp-version: 22.2
    - name: Install Dependencies
      run: MIX_ENV=test mix deps.get
    - name: Run Tests
      env:
        PG_HOST: postgres
      run: mix test
